# central-postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-postgres
  template:
    metadata:
      labels:
        app: central-postgres
    spec:
      containers:
      - name: central-postgres
        image: sangrk/postgres-pgbackrest:15
        env:
        - name: POSTGRES_DB
          value: HMS_CentralDB
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres123
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_INITDB_ARGS
          value: "--wal-level=replica --archive-mode=on --archive-command='pgbackrest --stanza=central archive-push %p'"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: central-postgres-data
          mountPath: /var/lib/postgresql/data
        - name: backup-volume
          mountPath: /backup
        - name: pgbackrest-config
          mountPath: /etc/pgbackrest
      volumes:
      - name: central-postgres-data
        persistentVolumeClaim:
          claimName: central-postgres-pvc
      - name: backup-volume
        persistentVolumeClaim:
          claimName: seaweed-filer-pvc
      - name: pgbackrest-config
        configMap:
          name: pgbackrest-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: central-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: central-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: central-postgres