pgpool:
  configuration: |-
    log_statement = 'all'
    log_per_node_statement = on
    debug_level = 1
    log_connections = on
    log_disconnections = on
    enable_load_balance = on
    backend_clustering_mode = streaming_replication
    load_balance_mode = on
    statement_level_load_balance = on
    disable_load_balance_on_write = transaction
    app_name_redirect_preference_list = 'reader:1'
    prefer_query_route_to_primary = off
    database_redirect_preference_list = 'HMS_CentralDB:1'
postgresql:
  postgresqlConfiguration:
    shared_preload_libraries: "repmgr,pgaudit,pg_stat_statements"
  replicaCount: 2